version: '3'
 
services:

  rabbitmq:
    image: rabbitmq
    ports:
      - "5672:5672"
    profiles: ["all", "ufe"]

  redis:
    image: redis:7.0.11-alpine
    ports:
      - "6379:6379"
    profiles: [ "all", "ufe"]

  mysql-db:
    image: mysql
    ports:
      - "3307:3306"
    environment:
      MYSQL_DATABASE: db_banka1
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DB: mysql
#    volumes:
#      - db-user:/var/lib/mysql/data
    profiles: ["all", "exchange", "ufe", "flask"]

  mongo-db:
    image: mongo
    expose:
      - "27017"
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: banka1_mongodb
      MONGO_INITDB_ROOT_PASSWORD: banka1_mongodb
    restart: on-failure
    profiles: ["all", "contracts", "mongo"]

  user-service:
    image: harbor.k8s.elab.rs/banka-1/user-service:latest
    build: ./user-service
    environment:
      spring.datasource.hikari.jdbcUrl: jdbc:mysql://mysql-db:3306/db_banka1
    ports:
      - "8080:8080"
    links:
      - mysql-db
    depends_on:
      - mysql-db
    restart: on-failure
    profiles: ["all", "exchange", "ufe"]

  flask-api-service:
    image: harbor.k8s.elab.rs/banka-1/flask-api-service:latest
    build: ./flask-api-service
    ports:
      - "8888:8888"
    profiles: ["all", "exchange", "ufe", "flask"]

  exchange-service:
    image: harbor.k8s.elab.rs/banka-1/exchange-service:latest
    build: ./exchange-service
    environment:
      spring.datasource.hikari.jdbcUrl: jdbc:mysql://mysql-db:3306/db_banka1
    ports:
      - "8081:8081"
    links:
      - mysql-db
      - flask-api-service
      - rabbitmq
      - redis
      - user-service
    depends_on:
      - mysql-db
      - flask-api-service
      - rabbitmq
      - redis
      - user-service
    restart: on-failure
    profiles: [ "all", "ufe"]

  bank-service:
    image: harbor.k8s.elab.rs/banka-1/bank-service:latest
    build: ./bank-service
    environment:
      spring.datasource.hikari.jdbcUrl: jdbc:mysql://mysql-db:3306/db_banka1
    ports:
      - "8074:8074"
    links:
      - mysql-db
      - flask-api-service
    depends_on:
      - mysql-db
      - flask-api-service
    restart: on-failure
    profiles: ["all"]

  contracts-service:
    image: harbor.k8s.elab.rs/banka-1/contracts-service:latest
    build: ./contracts-service
    ports:
      - "8082:8082"
    depends_on:
      - mongo-db
    restart: on-failure
    profiles: ["all", "contracts"]

  companies-service:
    image: harbor.k8s.elab.rs/banka-1/companies-service:latest
    build: ./companies-service
    ports:
      - "8083:8083"
    depends_on:
      - mongo-db
    restart: on-failure
    profiles: [ "all", "companies" ]

volumes:
  mysql-db:
  mongo-db:
