apiVersion: v1
data:
  rootHost: JQ==
  rootPassword: cm9vdA==
  rootUser: cm9vdA==
kind: Secret
metadata:
  name: mysql-db-credentials
---
apiVersion: mysql.oracle.com/v2
kind: InnoDBCluster
metadata:
  name: mysql-db
spec:
  secretName: mysql-db-credentials
  tlsUseSelfSigned: true
  instances: 3
  router:
    instances: 1
