apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: user-service
  name: user-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: user-service
  template:
    metadata:
      labels:
        app: user-service
    spec:
      containers:
        - image: harbor.k8s.elab.rs/banka-1/user-service:latest
          imagePullPolicy: Always
          name: user-service
          env:
            - name: spring.datasource.hikari.jdbcUrl
              value: jdbc:mysql://mysql-db:3306/db_banka1?createDatabaseIfNotExist=true
            - name: spring.jpa.hibernate.ddl-auto
              value: update
            - name: password.reset.endpoint
              value: https://banka-1.k8s.elab.rs/reset-password
            - name: password.activate.endpoint
              value: https://banka-1.k8s.elab.rs/activate-password
          ports:
            - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: user-service
  name: user-service
spec:
  ports:
    - port: 8080
      protocol: TCP
      targetPort: 8080
  selector:
    app: user-service
  type: ClusterIP

